---
  copyright_image: "https://i.creativecommons.org/l/by-sa/4.0/80x15.png"
  copyright_image_link: "http://creativecommons.org/licenses/by-sa/4.0/"
  copyright_text: "Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
