---
  header_logo_url:
  header_logo_text: My project
  header_links:
    - label: Home
      link: /

#    - label: News
#      link: /news

    - label: Search DwC
      link: /resources/tw/filter/dwc_otus

    - label: Bibliography
      link: /resources/tw/filter/bibliography

    - label: About
      link: /about
